---
name: aurora
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: script
    scripts:
      - add_adoptium_repo.sh

  - type: dnf
    install:
      packages:
        - gwenview
        - mpv
        - stow
        - temurin-11-jdk
        - temurin-8-jdk
        - wine
    remove:
      packages:
        - libvirt
        - qemu

  - from-file: kde.yml

  - type: signing
