---
name: aurora
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  - type: script
    scripts:
      - add_adoptium_repo.sh

  - type: dnf
    repos:
      copr:
        - matinlotfali/KDE-Rounded-Corners
    install:
      packages:
        - gwenview
        - kcalc
        - kwin-effect-roundcorners
        - mpv
        - okular
        - stow
        - temurin-11-jdk
        - temurin-8-jdk
        - wine
    remove:
      packages:
        - libvirt
        - qemu

  - type: signing
