---
name: aurora
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/aurora-dx
image-version: latest

modules:
  - type: rpm-ostree
    install:
      - adoptium-temurin-java-repository

  - type: rpm-ostree
    install:
        - temurin-8-jdk
        - temurin-11-jdk

  - type: dnf
    repos:
      copr:
        - matinlotfali/KDE-Rounded-Corners
    install:
      packages:
        - kwin-effect-roundcorners
        - mpv
        - stow
        - wine

  - type: signing
