---
name: aurora
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bluefin
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - add_adoptium_repo.sh

  - type: dnf
    repos:
      copr:
        - wezfurlong/wezterm-nightly
    install:
      packages:
        - dolphin
        - gwenview
        - kcalc
        - kvantum
        - mpv
        - neovim
        - stow
        - temurin-11-jdk
        - temurin-8-jdk
        - wezterm
        - wine

  - from-file: niri.yml

  - type: script
    scripts:
      - dx.sh

  - type: signing
