---
name: aurora
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/bluefin-dx
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: /

  - type: script
    scripts:
      - add_adoptium_repo.sh

  - from-file: niri.yml

  - type: dnf
    install:
      packages:
        - mpv
        - neovim
        - stow
        - temurin-11-jdk
        - temurin-8-jdk
        - wine

  - type: signing
